name: GithubActions Example 002
run-name: ${{ github.actor }} Node.js
on:
  push:
   branches: [main]
  pull_request:
   branches: [main] 
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
     matrix: [17,18,19]
    steps:
      - name: Checkout app 
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
         node-version: ${{ matrix.node-version }}
         cache: npm
      - run: npm ci   
      - run: npm run build   
      - run: npm run test